/*
 * HOST_TEST replacement for the fixed DRAM layout of memory_map.h.
 *
 * The firmware addresses all of its metadata tables and data buffers through 32-bit
 * integers. On the host those integers are offsets into one contiguous arena that
 * host_mem_init() maps below the 4 GiB boundary (so that unsigned int <-> pointer
 * conversions stay lossless). The relative layout mirrors memory_map.h: the same
 * tables are chained in the same order, only the three hard-coded region bases are
 * replaced by a runtime base plus fixed-size gaps.
 */
#ifndef HOST_MEMORY_MAP_H
#define HOST_MEMORY_MAP_H

extern unsigned int hostDramBaseAddr;

#define HOST_RESERVED_DATA_BUFFER_SIZE		0x00400000
#define HOST_TEMPORARY_PAY_LOAD_SIZE		0x00010000

#define DRAM_START_ADDR					(hostDramBaseAddr)

#define MEMORY_SEGMENTS_START_ADDR		DRAM_START_ADDR
#define MEMORY_SEGMENTS_END_ADDR		(DRAM_START_ADDR - 1)

#define NVME_MANAGEMENT_START_ADDR		DRAM_START_ADDR
#define NVME_MANAGEMENT_END_ADDR		(DRAM_START_ADDR - 1)

#define RESERVED0_START_ADDR			DRAM_START_ADDR
#define RESERVED0_END_ADDR				(DRAM_START_ADDR - 1)

#define FTL_MANAGEMENT_START_ADDR		DRAM_START_ADDR
//for data buffer
#define DATA_BUFFER_BASE_ADDR 					(FTL_MANAGEMENT_START_ADDR)
#define TEMPORARY_DATA_BUFFER_BASE_ADDR			(DATA_BUFFER_BASE_ADDR + AVAILABLE_DATA_BUFFER_ENTRY_COUNT * BYTES_PER_DATA_REGION_OF_SLICE)
#define SPARE_DATA_BUFFER_BASE_ADDR				(TEMPORARY_DATA_BUFFER_BASE_ADDR + AVAILABLE_TEMPORARY_DATA_BUFFER_ENTRY_COUNT * BYTES_PER_DATA_REGION_OF_SLICE)
#define TEMPORARY_SPARE_DATA_BUFFER_BASE_ADDR	(SPARE_DATA_BUFFER_BASE_ADDR + AVAILABLE_DATA_BUFFER_ENTRY_COUNT * BYTES_PER_SPARE_REGION_OF_SLICE)
#define RESERVED_DATA_BUFFER_BASE_ADDR 			(TEMPORARY_SPARE_DATA_BUFFER_BASE_ADDR + AVAILABLE_TEMPORARY_DATA_BUFFER_ENTRY_COUNT * BYTES_PER_SPARE_REGION_OF_SLICE)
//for nand request completion
#define COMPLETE_FLAG_TABLE_ADDR			(RESERVED_DATA_BUFFER_BASE_ADDR + HOST_RESERVED_DATA_BUFFER_SIZE)
#define STATUS_REPORT_TABLE_ADDR			(COMPLETE_FLAG_TABLE_ADDR + sizeof(COMPLETE_FLAG_TABLE))
#define ERROR_INFO_TABLE_ADDR				(STATUS_REPORT_TABLE_ADDR + sizeof(STATUS_REPORT_TABLE))
#define TEMPORARY_PAY_LOAD_ADDR				(ERROR_INFO_TABLE_ADDR+ sizeof(ERROR_INFO_TABLE))
// for buffers
#define DATA_BUFFER_MAP_ADDR		 		(TEMPORARY_PAY_LOAD_ADDR + HOST_TEMPORARY_PAY_LOAD_SIZE)
#define DATA_BUFFFER_HASH_TABLE_ADDR		(DATA_BUFFER_MAP_ADDR + sizeof(DATA_BUF_MAP))
#define TEMPORARY_DATA_BUFFER_MAP_ADDR 		(DATA_BUFFFER_HASH_TABLE_ADDR + sizeof(DATA_BUF_HASH_TABLE))
// for map tables
#define LOGICAL_SLICE_MAP_ADDR				(TEMPORARY_DATA_BUFFER_MAP_ADDR + sizeof(TEMPORARY_DATA_BUF_MAP))
#define VIRTUAL_SLICE_MAP_ADDR				(LOGICAL_SLICE_MAP_ADDR + sizeof(LOGICAL_SLICE_MAP))
#define VIRTUAL_BLOCK_MAP_ADDR				(VIRTUAL_SLICE_MAP_ADDR + sizeof(VIRTUAL_SLICE_MAP))
#define PHY_BLOCK_MAP_ADDR					(VIRTUAL_BLOCK_MAP_ADDR + sizeof(VIRTUAL_BLOCK_MAP))
#define BAD_BLOCK_TABLE_INFO_MAP_ADDR		(PHY_BLOCK_MAP_ADDR + sizeof(PHY_BLOCK_MAP))
#define VIRTUAL_DIE_MAP_ADDR				(BAD_BLOCK_TABLE_INFO_MAP_ADDR + sizeof(BAD_BLOCK_TABLE_INFO_MAP))
// for GC victim selection
#define GC_VICTIM_MAP_ADDR					(VIRTUAL_DIE_MAP_ADDR + sizeof(VIRTUAL_DIE_MAP))
// for request pool
#define REQ_POOL_ADDR						(GC_VICTIM_MAP_ADDR + sizeof(GC_VICTIM_MAP))
// for dependency table
#define ROW_ADDR_DEPENDENCY_TABLE_ADDR		(REQ_POOL_ADDR + sizeof(REQ_POOL))
// for request scheduler
#define DIE_STATE_TABLE_ADDR				(ROW_ADDR_DEPENDENCY_TABLE_ADDR + sizeof(ROW_ADDR_DEPENDENCY_TABLE))
#define RETRY_LIMIT_TABLE_ADDR				(DIE_STATE_TABLE_ADDR + sizeof(DIE_STATE_TABLE))
#define WAY_PRIORITY_TABLE_ADDR 			(RETRY_LIMIT_TABLE_ADDR + sizeof(RETRY_LIMIT_TABLE))

#define FTL_MANAGEMENT_END_ADDR				((WAY_PRIORITY_TABLE_ADDR + sizeof(WAY_PRIORITY_TABLE))- 1)

#define RESERVED1_START_ADDR				(FTL_MANAGEMENT_END_ADDR + 1)
#define RESERVED1_END_ADDR					(FTL_MANAGEMENT_END_ADDR)

#define DRAM_END_ADDR						(FTL_MANAGEMENT_END_ADDR)

#endif /* HOST_MEMORY_MAP_H */
